# Generated by Django 5.2.13 on 2026-07-05 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('lab', 'Lab')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('incomplete', 'Incomplete'), ('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='free', max_length=30)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User subscription',
                'verbose_name_plural': 'User subscriptions',
            },
        ),
    ]
